CC = g++
FLAGS = -std=c++11 -O2 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm
FILES = main.cpp TArbitraryPrecise.cpp 
PROG = long
long:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o long